services:

  revue-recognition:
    image: letsdothisshared/revue-recognition
    container_name: ${RECOGNITION_HOST}
    build:
      context: .
      dockerfile: recognition/Dockerfile
    restart: on-failure
    ports:
      - ${RECOGNITION_PORT}:${RECOGNITION_PORT}
    environment:
      - RECOGNITION_PORT=${RECOGNITION_PORT}
    depends_on:
      - revue-camera-1
      - revue-camera-2
    networks:
      - my-net

networks:
  my-net:
    name: revue-network
    external: true
