version: '3.8'

services:

  revue-sensor-1:
    image: revue-sensor
    container_name: revue-sensor-1
    build:
      context: .
      dockerfile: ./sensor/Dockerfile
    restart: on-failure
    environment:
      - SENSOR_CODE=sen-01
    ports:
      - ${SENSOR_PORT_1}:${SENSOR_PORT_1}
    depends_on:
      - ${KAFKA_HOST}
      - ${MONITORING_HOST}
    networks:
      - my_net

  revue-sensor-2:
    image: revue-sensor
    container_name: revue-sensor-2
    build:
      context: .
      dockerfile: ./sensor/Dockerfile
    restart: on-failure
    environment:
      - SENSOR_CODE=sen-02
    ports:
      - ${SENSOR_PORT_2}:${SENSOR_PORT_2}
    depends_on:
      - ${KAFKA_HOST}
      - ${MONITORING_HOST}
    networks:
      - my_net

#  revue-sensor-2:
#    image: revue-sensor
#    container_name: revue-sensor-2
#    build:
#      context: .
#      dockerfile: ./sensor/Dockerfile
#    restart: on-failure
#    environment:
#      - SENSOR_CODE=sen-02
#    ports:
#      - ${SENSOR_PORT_2}:${SENSOR_PORT_2}
#    depends_on:
#      - ${KAFKA_HOST}

#  revue-sensor-3:
#    image: revue-sensor
#    container_name: revue-sensor-3
#    build:
#      context: .
#      dockerfile: ./sensor/Dockerfile
#    restart: on-failure
#    environment:
#      - SENSOR_CODE=sen-03
#    ports:
#      - ${SENSOR_PORT_3}:${SENSOR_PORT_3}
#    depends_on:
#      - ${KAFKA_HOST}
#      - ${MONITORING_HOST}

networks:
  my_net:
    external: true
    name: revue_network