version: '3.8'

services:

  revue-zookeeper:
    image: bitnami/zookeeper:latest
    container_name: revue-zookeeper
    ports:
      - ${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - my-net

  revue-kafka:
    image: bitnami/kafka:latest
    container_name: ${KAFKA_HOST}
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
      - ${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://revue-kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_ZOOKEEPER_CONNECT=revue-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_MESSAGE_MAX_BYTES=200000000
#    volumes:
#      - kafka_data:/bitnami/kafka
#      - ~/kafka/data/zookeeper_data:/var/lib/zookeeper/data
#      - ~/kafka/data/zookeeper_log:/var/lib/zookeeper/log
    depends_on:
      - revue-zookeeper
    networks:
      - my-net
#volumes:
#  kafka_data:
#    driver: local

networks:
  my-net:
    name: revue-network
    external: true